'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class Detail2

    '''<summary>
    '''IDStudent_Detail control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents IDStudent_Detail As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''FirstName_Detail control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents FirstName_Detail As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''LastName_Detail control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LastName_Detail As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''Enrollment_Detail control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Enrollment_Detail As Global.System.Web.UI.WebControls.Label
End Class
