'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class Index

    '''<summary>
    '''FirstName_Sr control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents FirstName_Sr As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''LastName_Sr control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LastName_Sr As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''Enrollment_Sr control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Enrollment_Sr As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''Bt_Search control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Bt_Search As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''IDStudent_ASC control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents IDStudent_ASC As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''IDStudent_DESC control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents IDStudent_DESC As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''FirstName_ASC control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents FirstName_ASC As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''FirstName_DESC control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents FirstName_DESC As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''LastName_ASC control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LastName_ASC As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''LastName_DESC control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LastName_DESC As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''Enrollment_ASC control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Enrollment_ASC As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''Enrollment_DESC control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Enrollment_DESC As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''GridView control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents GridView As Global.System.Web.UI.WebControls.GridView
End Class
