'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class Index2

    '''<summary>
    '''FirstName_Sr control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents FirstName_Sr As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''Title_Sr control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Title_Sr As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''ddlGrade_sr control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlGrade_sr As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''Bt_Search control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Bt_Search As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''IDEnrollment_ASC control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents IDEnrollment_ASC As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''IDEnrollment_DESC control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents IDEnrollment_DESC As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''FirstName_ASC control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents FirstName_ASC As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''FirstName_DESC control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents FirstName_DESC As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''Title_ASC control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Title_ASC As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''Title_DESC control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Title_DESC As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''Grade_ASC control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Grade_ASC As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''Grade_DESC control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Grade_DESC As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''GridView control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents GridView As Global.System.Web.UI.WebControls.GridView
End Class
